global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'k8s-manager'
    static_configs:
      - targets: ['backend:8080']
    metrics_path: '/api/v1/actuator/prometheus'
    scheme: 'http'
